### ISSUE TITLE
Update @fabric/http in README

### ISSUE THREAD

**Issue by martindale** [FabricLabs/fabric#94]
README should be updated to reflect current status of `@fabric/http`

**TODO**
- [x] FabricLabs/fabric-http#8
- [x] FabricLabs/fabric-http#9
- [x] FabricLabs/fabric-http#18
- [x] FabricLabs/fabric-http#23
